# Generated by Django 3.2.8 on 2022-02-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asignup',
            new_name='book_asignup',
        ),
        migrations.RenameModel(
            old_name='book',
            new_name='book_book',
        ),
    ]
