# Generated by Django 3.2.8 on 2022-02-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220213_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book_asignup',
            new_name='asignup',
        ),
        migrations.RenameModel(
            old_name='book_book',
            new_name='book',
        ),
    ]
